### ISSUE TITLE
How were the JSON files generated?

### ISSUE THREAD

**Issue by sumeet-bansal** [andportnoy/escapesd#1]
Didn't see any scripts to scrape the data or anything.

**Comment by andportnoy** [comment]
Question is on point. I basically didn't save the code that produces the JSONs from the raw data, am going to reproduce it soon.

**Comment by andportnoy** [comment]
@sumeet-bansal Updated repo to include the code that scrapes/cleans the data and a demo notebook that runs through all the steps.
