### ISSUE TITLE
CAPEs are now hidden behind the SSO

### ISSUE THREAD

**Issue by andportnoy** [andportnoy/escapesd#9]

**Comment by niemasd** [comment]
You can probably use some "download all links on page" functionality in Google Chrome or whatever browser you're using (after signing in with SSO and Duo), such as [this one](https://chrome.google.com/webstore/detail/simple-mass-downloader/abdkkegmcbiomijcbdaodaflgehfffed?hl=en-US). Once you have saved HTML files, it should be easy to parse them locally in bulk

**Comment by andportnoy** [comment]
@niemasd My current plan is to implement a conditional wait in Selenium that blocks until the human driver enters the SSO info.

**Comment by niemasd** [comment]
Ah, good idea :-)

**Comment by andportnoy** [comment]
Addressed in 5768ee5ee37c97a804388b7e16f744d6f13a692b.
